FROM pdal/dependencies:ubuntu

WORKDIR /tmp

RUN apt update \
 && apt install -y libcurl4-openssl-dev liblzma-dev libjsoncpp-dev libssl-dev

RUN git clone https://github.com/PDAL/PDAL.git \
 && cd PDAL; mkdir build; cd build \
 && cmake .. -DWITH_LAZPERF=ON -DWITH_LASZIP=ON -DCMAKE_INSTALL_PREFIX=/usr/local \
 && make install

RUN git clone https://github.com/connormanning/entwine.git \
 && cd entwine; mkdir build; cd build \
 && cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local \
 && make install

RUN git clone https://github.com/eidheim/Simple-Web-Server.git simple-web \
 && cd simple-web; mkdir build; cd build \
 && cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local \
 && make install

RUN git clone https://github.com/jw3/greyhound.git -b jw3/ept \
 && cd greyhound; mkdir build; cd build \
 && cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local \
 && make install

#
# -------------------------------------------
#

FROM pdal/ubuntu:master

MAINTAINER John Wass <jwass3@gmail.com>

ENV EPT_GH_BUILDER_VERSION 0.1
ENV EPT_GH_HTTP_PORT 8080

LABEL io.k8s.display-name="EPT on Greyhound Builder" \
      io.k8s.description="Entwine Point Tile (EPT) builder with Greyhound" \
      io.openshift.expose-services="${EPT_HTTP_PORT}:http" \
      io.openshift.tags="builder,ept,entwine,greyhound,pointcloud" \
      io.openshift.s2i.scripts-url="image:///usr/libexec/s2i"

COPY s2i/bin/ /usr/libexec/s2i

COPY --from=0 /usr/local /usr/local

RUN apt update \
 && apt install -y libboost-system1.65.1 \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir /opt/app-root /entwine \
 && chown -R 1001:0 /opt/app-root /entwine /usr/libexec/s2i \
 && chmod -R g+rwX  /opt/app-root /entwine /usr/libexec/s2i

WORKDIR /opt/app-root

USER 1001

EXPOSE 8080

ENTRYPOINT []
CMD ["/usr/libexec/s2i/usage"]
